[package]
name = "usecase"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.*"
async-trait = "0.1.*"
serde = { version = "1.0.*", features = ["derive"] }
thiserror = "1.0.*"

domain = { path = "../domain" }
