[package]
name = "domain"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.*"
async-trait = "0.1.*"
thiserror = "1.0.*"
time = { version = "0.3.*", features = ["serde"] }
uuid = { version = "1.5.*", features = ["v4"] }

macros = { path = "../macros" }
