[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4.*"
anyhow = "1.0.*"
controller = { path = "../controller" }
tokio = { version = "1.33.0", features = ["macros", "rt-multi-thread"] }
